name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - rzadp/prerequisites


jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ["ubuntu:24.04", "debian:12.5"]
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3

      - name: Run the prerequisites script
        run: |
          ./.github/scripts/$(echo "${{ matrix.container }}" | cut -d':' -f1)-prerequisites.sh

      # - name: Rust compilation prerequisites
      #   run: |
      #     sudo apt update
      #     sudo apt install -y \
      #       protobuf-compiler
      #     rustup target add wasm32-unknown-unknown
      #     rustup component add rustfmt clippy rust-src

      # We've run into out-of-disk error when compiling Polkadot in the next step, so we free up some space this way.
      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # 1.3.1
      #   with:
      #     android: true # This alone is a 12 GB save.
      #     # We disable the rest because it caused some problems. (they're enabled by default)
      #     # The Android removal is enough.
      #     dotnet: false
      #     haskell: false
      #     large-packages: false
      #     swap-storage: false

      # - name: Build the template
      #   run: cargo build
      #   timeout-minutes: 90

      # - name: Run clippy
      #   run: |
      #     SKIP_WASM_BUILD=1 cargo clippy --all-targets --locked --workspace --quiet
      #     SKIP_WASM_BUILD=1 cargo clippy --all-targets --all-features --locked --workspace --quiet
      #   timeout-minutes: 30

      # - name: Run the tests
      #   run: cargo test
      #   timeout-minutes: 15

      # - name: Build the docs
      #   run: cargo doc --all-features --workspace --no-deps
      #   timeout-minutes: 15
